include theos/makefiles/common.mk

LIBRARY_NAME = UICore
ADDITIONAL_LDFLAGS += -framework UIKit -framework Foundation -framework CoreFoundation 
LOCAL_INSTALL_PATH = /Library/UISettings/UICore/
UICore_FILES = uicore.mm

include $(THEOS_MAKE_PATH)/library.mk
