include theos/makefiles/common.mk

LIBRARY_NAME = UICore
UICore_PRIVATE_FRAMEWORKS = UIKit Foundation CoreFoundation 
LOCAL_INSTALL_PATH = /Library/UISettings/UICore/
UICore_FILES = uicore.mm

include $(THEOS_MAKE_PATH)/library.mk
