include theos/makefiles/common.mk

LIBRARY_NAME = uitoggles
uitoggles_FILES = uitoggles.xm
uitoggles_PRIVATE_FRAMEWORKS = UIKit CoreGraphics GraphicsServices MediaPlayer
LOCAL_INSTALL_PATH = /Library/UISettings/

include $(THEOS_MAKE_PATH)/library.mk
